name: Upload Artifact Example
 
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Create a file
      run: echo "Hello, World!" > my-artifact.txt
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: my-artifact.txt
